# Generated by Django 5.1.3 on 2024-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_name',
            field=models.CharField(max_length=55),
        ),
    ]
